/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Iconfont: (typeof import('./src/components/iconfont.vue'))['default']
    IconfontIcon: typeof import('./src/components/IconfontIcon.vue')['default']
    NetIcon: typeof import('./src/components/NetIcon.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
