/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DarkModeToggle: typeof import('./src/components/Themes/DarkModeToggle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FullScreen: typeof import('./src/components/Themes/FullScreen.vue')['default']
    Iconfont: (typeof import('./src/components/iconfont.vue'))['default']
    IconfontIcon: typeof import('./src/components/Icon/IconfontIcon.vue')['default']
    Iconify: typeof import('./src/components/Icon/Iconify.vue')['default']
    IconList: typeof import('./src/components/Icon/IconList.vue')['default']
    IconPicker: typeof import('./src/components/Icon/IconPicker.vue')['default']
    NetIcon: typeof import('./src/components/Icon/NetIcon.vue')['default']
    ReloadPrompt: typeof import('./src/components/Icon/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
